# Generated by Django 5.0.1 on 2024-01-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_order_client_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default='cart_not_confirmed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, default='cart_not_confirmed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=1440, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_min',
            field=models.ImageField(max_length=200, upload_to='static'),
        ),
    ]
