# Generated by Django 5.0.1 on 2024-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_order_order_date_alter_order_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
