# Generated by Django 4.2.9 on 2024-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_alter_order_client_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=1440, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_min',
            field=models.ImageField(max_length=200, upload_to='images'),
        ),
    ]
